Repository ehcache/ehcache3, pull requests merged in 2018-02, with the labels that each got.

#2279 Upgrade to asm 6, jetty 9 and servlet API 3.1
  demos/00-NoCache/src/main/java/org/ehcache/demos/peeper/PeeperServlet.java
  demos/00-NoCache/src/main/java/org/ehcache/demos/peeper/PeeperServletContextListener.java
  demos/00-NoCache/src/main/webapp/WEB-INF/web.xml
  demos/01-CacheAside/src/main/java/org/ehcache/demos/peeper/PeeperServlet.java
  demos/01-CacheAside/src/main/java/org/ehcache/demos/peeper/PeeperServletContextListener.java
  demos/01-CacheAside/src/main/webapp/WEB-INF/web.xml
  demos/build.gradle
  docs/src/docs/asciidoc/user/examples.adoc
  impl/build.gradle
  impl/src/test/java/org/ehcache/impl/serialization/SerializerTestUtilities.java
Labels: under review

#2248 Developer Documentation Integration
  docs/src/docs/asciidoc/developer/design.basics.asciidoc
  docs/src/docs/asciidoc/developer/design.bootstrapping.asciidoc
  docs/src/docs/asciidoc/developer/design.tiering.asciidoc
  docs/src/docs/asciidoc/developer/module.api.asciidoc
  docs/src/docs/asciidoc/developer/module.clustering.asciidoc
  docs/src/docs/asciidoc/developer/module.core.asciidoc
  docs/src/docs/asciidoc/developer/module.impl.asciidoc
  docs/src/docs/asciidoc/developer/module.xa.asciidoc
Labels: documentation

#2281 Add index file and align extensions with the user doc
  docs/src/docs/asciidoc/developer/design.basics.adoc
  docs/src/docs/asciidoc/developer/design.bootstrapping.adoc
  docs/src/docs/asciidoc/developer/design.tiering.adoc
  docs/src/docs/asciidoc/developer/index.adoc
  docs/src/docs/asciidoc/developer/module.api.adoc
  docs/src/docs/asciidoc/developer/module.clustering.adoc
  docs/src/docs/asciidoc/developer/module.core.adoc
  docs/src/docs/asciidoc/developer/module.impl.adoc
  docs/src/docs/asciidoc/developer/module.xa.adoc
Labels: under review

#2268 Resilience documentation
  clustered/client/src/test/java/org/ehcache/clustered/client/docs/Resilience.java
  docs/README.adoc
  docs/build.gradle
  docs/src/docs/asciidoc/user/index.adoc
  docs/src/docs/asciidoc/user/menu.adoc
  docs/src/docs/asciidoc/user/resilience.adoc
Labels: under review

#2285 Issue #2215 Add note in docs about the limitations of shared pool
  docs/src/docs/asciidoc/user/clustered-cache.adoc
Labels: under review

#2288 Use withResilienceStrategy to set the resilience strategy
  clustered/integration-test/src/test/java/org/ehcache/clustered/replication/DuplicateTest.java
Labels: under review

#2284 Test client doesn't freeze when server is down (close #2202)
  clustered/integration-test/build.gradle
  clustered/integration-test/src/test/java/org/ehcache/clustered/TerminatedServerTest.java
  clustered/integration-test/src/test/java/org/ehcache/clustered/management/AbstractClusteringManagementTest.java
Labels: under review

#2173 Design document on resilience
  docs/README.adoc
  docs/src/docs/asciidoc/developer/design.resilience.adoc
  docs/src/docs/asciidoc/developer/index.adoc
Labels: under review

#2290 Upgrade of platform + core
  gradle.properties
Labels: under review

#914 Initial proposal on clustered cache operations
  docs/build.gradle
  docs/src/docs/asciidoc/developer/clustered.adoc
  docs/src/docs/uml/cache-through-sequence.puml
  docs/src/docs/uml/passive-sync-solution-four.puml
  docs/src/docs/uml/passive-sync-solution-one.puml
  docs/src/docs/uml/passive-sync-solution-three.puml
  docs/src/docs/uml/passive-sync-solution-two.puml
  docs/src/docs/uml/putIfAbsentUml.puml
Labels: clustering, under review

#2292 Add now working termination tests because of the lease principle
  clustered/integration-test/src/test/java/org/ehcache/clustered/TerminatedServerTest.java
  clustered/integration-test/src/test/java/org/ehcache/clustered/replication/DuplicateTest.java
Labels: under review

#2295 No need to catch the exception anymore. Was fixed in terracotta-core
  clustered/integration-test/src/test/java/org/ehcache/clustered/TerminatedServerTest.java
Labels: under review

#2294 Grammar fixes on resilience doc
  docs/src/docs/asciidoc/user/resilience.adoc
Labels: under review

#2297 Management reconnect #2203
  clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/ConnectionState.java
  clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/DefaultClusteringService.java
  clustered/client/src/main/java/org/ehcache/clustered/client/service/ClusteringService.java
  clustered/integration-test/src/test/java/org/ehcache/clustered/management/AbstractClusteringManagementTest.java
  clustered/integration-test/src/test/java/org/ehcache/clustered/management/ManagementClusterConnectionTest.java
  gradle.properties
  management/src/main/java/org/ehcache/management/cluster/DefaultClusteringManagementService.java
Labels: under review

#2299 :arrow_up: Upgrade of terracotta dependencies
  gradle.properties
Labels: under review

#2301 Unwanted gradle property
  gradle.properties
Labels: under review

#2303 Remove all unchecked warnings
  impl/src/main/java/org/ehcache/config/builders/CacheConfigurationBuilder.java
  impl/src/main/java/org/ehcache/impl/config/resilience/DefaultResilienceStrategyConfiguration.java
  impl/src/main/java/org/ehcache/impl/config/resilience/DefaultResilienceStrategyProviderConfiguration.java
  impl/src/main/java/org/ehcache/impl/internal/spi/resilience/DefaultResilienceStrategyProvider.java
  impl/src/main/java/org/ehcache/impl/internal/spi/resilience/DefaultResilienceStrategyProviderFactory.java
  impl/src/test/java/org/ehcache/config/builders/CacheConfigurationBuilderTest.java
  impl/src/test/java/org/ehcache/impl/internal/spi/resilience/DefaultResilienceStrategyProviderFactoryTest.java
  impl/src/test/java/org/ehcache/impl/internal/spi/resilience/DefaultResilienceStrategyProviderTest.java
  impl/src/test/java/org/ehcache/test/MockitoUtil.java
Labels: under review

#2304 BasicCacheReconnectTest should extends ClusteredTests to run correctly in an IDE
  clustered/integration-test/src/test/java/org/ehcache/clustered/reconnect/BasicCacheReconnectTest.java
Labels: under review

#2306 :arrow_up: Bump up Terracotta dependencies to GA release versions
  clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/ConnectionState.java
  gradle.properties
Labels: under review

#2305 Fix #2289: Management provider information lost after failover
  clustered/integration-test/src/test/java/org/ehcache/clustered/management/AbstractClusteringManagementTest.java
  clustered/integration-test/src/test/java/org/ehcache/clustered/management/AfterFailoverManagementServiceTest.java
  clustered/integration-test/src/test/java/org/ehcache/clustered/management/ClusteringManagementServiceTest.java
  clustered/integration-test/src/test/java/org/ehcache/clustered/management/DiagnosticTest.java
  clustered/integration-test/src/test/java/org/ehcache/clustered/util/BeforeAll.java
  clustered/integration-test/src/test/java/org/ehcache/clustered/util/BeforeAllRule.java
  clustered/server/src/main/java/org/ehcache/clustered/server/ClusterTierManagerActiveEntity.java
  clustered/server/src/main/java/org/ehcache/clustered/server/ClusterTierManagerPassiveEntity.java
  clustered/server/src/main/java/org/ehcache/clustered/server/management/ClusterTierManagement.java
  clustered/server/src/main/java/org/ehcache/clustered/server/management/Management.java
  clustered/server/src/main/java/org/ehcache/clustered/server/store/ClusterTierActiveEntity.java
  clustered/server/src/main/java/org/ehcache/clustered/server/store/ClusterTierPassiveEntity.java
  gradle.properties
Labels: under review

#2308 Advance development version to 3.5.1-SNAPSHOT
  build.gradle
Labels: under review
